os:
  - linux

dist: trusty
sudo: required

language: node_js
node_js:
  - "12"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install @angular/cli
  - npm install minimatch@3.0.2
  - npm install
  - npm install ng-common

install:
  - npm install

script:
  - cd client
  - ng lint
  - npm run test -headless
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js

