os:
  - linux

dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli
  - npm install -g karma
  - npm install

script:
  - cd client
  - npm install
  - ng build
  - npm run test -- --no-watch --no-progress --browsers=Chrome
  - cd ..
  - npm run test -- --no-watch --no-progress --browsers=Chrome
  - npm stop test -- --no-watch --no-progress --browsers=Chrome


