version: '3.1'

services:

  osrm-backend:
    container_name: alsace_osrm-backend
    ports:
      - 5000:5000
    volumes:
      - osrm:/data
    build:
      context: ./docker/osrm/
      dockerfile: Dockerfile

  mariadb:
    container_name: alsace_mariadb
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    restart: always
    expose:
      - 3306

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: alsace_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb:3306
      MYSQL_ROOT_PASSWORD: root
    links:
      - mariadb

  server:
    depends_on:
      - mariadb
    container_name: alsace_server
    restart: always
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - '.:/home/node/app'
    ports:
      - 8080:8080

  client:
    container_name: alsace_client
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    volumes:
      - '.:/home/node/app'
    ports:
      - 80:8100
    depends_on:
      - server

#  web:
#    build:
#      context: .
#      dockerfile: docker/nginx/Dockerfile
#    ports:
#      - 80:80
#    depends_on:
#      - client

volumes:
  dbdata:
  mysql: {}
  osrm:
